version: '3'

services:
  db: mysql:8.0
  container_name: strafalarius_cont
  restart: unless-stopped
  environment: 
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    MYSQL_DATABASE: ${MYSQL_DATABASE}
  ports:
    - ${MYSQL_PORT}:3306
  volumes:
    - ./db/dataStorage_strafalariusDB:/var/lib/mysql
    - ./db/init:/docker-entrypoint-initdb.d