-- MySQL Script generated by MySQL Workbench
-- lun 06 may 2024 15:23:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Schema strafalariusDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `strafalariusDB` DEFAULT CHARACTER SET utf8 ;
USE `strafalariusDB` ;

-- -----------------------------------------------------
-- Table `strafalariusDB`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strafalariusDB`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre_cliente` VARCHAR(50) NOT NULL,
  `apellido_cliente` VARCHAR(50) NOT NULL,
  `telefono_cliente` VARCHAR(20) NOT NULL,
  `email_cliente` VARCHAR(100) NOT NULL,
  `direccion_cliente` VARCHAR(100) NULL,
  `membresia_cliente` VARCHAR(45),
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `id_cliente_UNIQUE` (`id_cliente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `strafalariusDB`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strafalariusDB`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre_producto`VARCHAR(45) NOT NULL,
  `talla_producto` VARCHAR(10) NOT NULL,
  `color_producto` VARCHAR(20) NOT NULL,
  `estacion_producto` VARCHAR(45) NOT NULL,
  `precio_producto` FLOAT NOT NULL,
  `descuento_producto` INT NULL,
  PRIMARY KEY (`id_producto`),
  UNIQUE INDEX `id_producto_UNIQUE` (`id_producto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `strafalariusDB`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strafalariusDB`.`vendedor` (
  `id_vendedor` INT NOT NULL AUTO_INCREMENT,
  `nombre_vendedor` VARCHAR(50) NOT NULL,
  `origen_vendedor` VARCHAR(45) NULL,
  `categoria_vendedor` TINYINT NOT NULL,
  PRIMARY KEY (`id_vendedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `strafalariusDB`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strafalariusDB`.`compra` (
  `id_compra` INT NOT NULL,
  `fk_cliente_id` INT NOT NULL,
  `fk_vendedor_id` INT NOT NULL,
  INDEX `fk_cliente_has_vendedor_cliente1_idx` (`fk_cliente_id` ASC) VISIBLE,
  PRIMARY KEY (`id_compra`),
  INDEX `fk_vendedor_id_idx` (`fk_vendedor_id` ASC) VISIBLE,
  UNIQUE INDEX `id_compra_UNIQUE` (`id_compra` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_id`
    FOREIGN KEY (`fk_cliente_id`)
    REFERENCES `strafalariusDB`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendedor_id`
    FOREIGN KEY (`fk_vendedor_id`)
    REFERENCES `strafalariusDB`.`vendedor` (`id_vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `strafalariusDB`.`detalleCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `strafalariusDB`.`detalleCompra` (
  `producto_id_detalleCompra` INT NOT NULL,
  `compra_id_detalleCompra` INT NOT NULL,
  PRIMARY KEY (`producto_id_detalleCompra`, `compra_id_detalleCompra`),
  INDEX `fk_idCompra_detalleCompra_idx` (`compra_id_detalleCompra` ASC) VISIBLE,
  CONSTRAINT `fk_idProducto_detalleCompra`
    FOREIGN KEY (`producto_id_detalleCompra`)
    REFERENCES `strafalariusDB`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idCompra_detalleCompra`
    FOREIGN KEY (`compra_id_detalleCompra`)
    REFERENCES `strafalariusDB`.`compra` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
